### ISSUE TITLE
Traceroute Support

### ISSUE THREAD

**Issue by looterz** [nogizhopaboroda/iponmap#1]
I was going to make something similar to this for myself, but this looks great already. It would be pretty awesome to have support for doing a visual trace-route from your source address to the target address shown on the map in real-time.

**Comment by nogizhopaboroda** [comment]
Thanks for the request! I thought about this but I wasn't sure someone needs it. 
Will implement soon.

**Comment by nogizhopaboroda** [comment]
@looterz done. update application.
Call iponmap with `-t` flag and pass any string which contains ip address. Like that:

``` shell
traceroute -n google.com | iponmap -t
```
