### ISSUE TITLE
iponmap domain-name

### ISSUE THREAD

**Issue by NatoBoram** [nogizhopaboroda/iponmap#5]
Similarly to #4, I'd like to be able to use `iponmap google.ca` and see it on the map rather than having to get its IP beforehand.

**Comment by nogizhopaboroda** [comment]
App is not supposed to work this way by design, it takes only ips. Everything else is other utils responsibilities. Instead you can do:
```sh
host google.ca | iponmap
```
or 
```sh
iponmap `host google.ca`
```
